config/routes.rb
Rails.application.routes.draw do 
  
	root "articles#index"
	#root "users#new"
	resources :articles do
    	resources :usercomments
  	end
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = "admin_users/omniauth_callbacks"
  devise_for :admin_users, devise_config
  ActiveAdmin.routes(self)
  devise_for :users
  #get ‘auth/:provider/callback’, to: ‘sessions#googleAuth’
  #get ‘auth/failure’, to: redirect(‘/’)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #:recoverable, :rememberable, :validatable,
 #  devise :database_authenticatable, 
 #         :omniauthable, :omniauth_providers => [:google_oauth2]

 #    def self.new_with_session(params, session)
	#   super.tap do |admin_user|
	#     if data = session["devise.google_oauth2_data"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
	#       admin_user.email = data["email"] if admin_user.email.blank?
	#     end
	#   end
	# end

	# def self.from_omniauth(auth)
	#   logger.info auth 
	#   where(provider: auth.provider, uid: auth.uid).first_or_create do |admin_user|
	#     admin_user.email = auth.info.email
	#     admin_user.password = Devise.friendly_token[0,20]
	#     admin_user.name = auth.info.name   # assuming the user model has a name
	#     #user.image = auth.info.image # assuming the user model has an image
	#   end
	# end
	# def self.password_required?
	# 	super && provider.blank?
	# end
	# def self.email_required?
	# 	super && provider.blank?
	# end
	devise :database_authenticatable, 
		   :recoverable, :rememberable, :validatable,
           :omniauthable, :omniauth_providers => [:google_oauth2]

    def self.new_with_session(params, session)
	  super.tap do |admin_user|
	    if data = session["devise.google_oauth2_data"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
	      admin_user.email = data["email"] if admin_user.email.blank?
	    end
	  end
	end

	def self.from_omniauth(auth)
		puts auth
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |admin_user|
	    admin_user.email = auth.info.email
	    admin_user.password = Devise.friendly_token[0,20]
	    #admin_user.name = auth.info.name   # assuming the user model has a name
	    #user.image = auth.info.image # assuming the user model has an image
	  end
	end
	def self.password_required?
		super && provider.blank?
	end
	def self.email_required?
		super && provider.blank?
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user
  has_many :usercomments,dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles,dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

#   def self.new_with_session(params, session)
#   super.tap do |user|
#     if data = session["devise.google_oauth2_data"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
#       user.email = data["gmail"] if user.email.blank?
#     end
#   end
# end

# def self.from_omniauth(auth)
#   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#     user.email = auth.info.email
#     user.password = Devise.friendly_token[0,20]
#     user.name = auth.info.name   # assuming the user model has a name
#     #user.image = auth.info.image # assuming the user model has an image
#   end
# end#          :omniauthable, :omniauth_providers => [:google_oauth2]

#   def self.new_with_session(params, session)
#   super.tap do |user|
#     if data = session["devise.google_oauth2_data"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
#       user.email = data["gmail"] if user.email.blank?
#     end
#   end
# end

# def self.from_omniauth(auth)
#   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#     user.email = auth.info.email
#     user.password = Devise.friendly_token[0,20]
#     user.name = auth.info.name   # assuming the user model has a name
#     #user.image = auth.info.image # assuming the user model has an image
#   end
# end
end

app/models/usercomment.rb
class Usercomment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/controllers/admin_users/omniauth_callbacks_controller.rb
class AdminUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    logger.info request.env["omniauth.auth"] 
    @admin_user = AdminUser.from_omniauth(request.env["omniauth.auth"])
    puts @admin_user["email"]
    if @admin_user.persisted?
      sign_in_and_redirect @admin_user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "google_oauth2") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      # @admin_user = AdminUser.create!(email: @admin_user["extra"]["raw_info"]["email"]+".fb",password: @admin_user["uid"])
      # sign_in_and_redirect @admin_user, :event => :authentication 
      redirect_to admin_dashboard_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before_action :authorize,except: [:index,:show]
  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :correct_user, only: [:edit,:update,:destroy]
  def index
  	@articles = Article.all 
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
    @user = current_user
    @article = @user.articles.new
  end

  def create
    @user = current_user
    @article = @user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    redirect_to article_path, notice: "you are not authorized" if @article.nil?
  end
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
    private
    def article_params
      params.require(:article).permit(:title, :body,:status)
    end

end

app/controllers/usercomments_controller.rb
class UsercommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @usercomment = @article.usercomments.create(usercomment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @usercomment = @article.usercomments.find(params[:id])
    @usercomment.destroy
    redirect_to article_path(@article)
  end

  private
    def usercomment_params
      params.require(:usercomment).permit( :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div> 
<% end %>

app/views/articles/_usercomments.html.erb
<p>
  <strong>Comment:</strong>
  <%= usercomment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [usercomment.article, usercomment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>


<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>
<%= link_to "ksd",new_admin_user_url %>
<div>
<%= link_to "New Article", new_article_path %>
</div>
<div>
	<% if user_signed_in? %>
		<%= current_user.email %> | <%= link_to "sign out", destroy_user_session_path,method: :delete %>
	<% else %>
		<%= link_to "sign up", new_user_registration_path %> | <%= link_to "sign in", new_user_session_path %>
	<% end %>
</div>
<%= yield %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>
@article.email = current_user.email

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>
<p>
	Writer
	<%= @article.user.email %>
</p>

<h2>Comments</h2>
<%= render @article.usercomments %>

<h2>Add a comment:</h2>
<%= render 'usercomments/form' %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/usercomments/_form.html.erb
<%= form_with model: [ @user,@article, @article.usercomments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/usercomments/_usercomment.html.erb
<p>
  <strong>Comment:</strong>
  <%= usercomment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [usercomment.article, usercomment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>